services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    volumes:
      - ./Database/Data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    ports:
      - "27017:27017"

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:password123@mongo1:27017/IMDB?authSource=admin
    depends_on:
      - mongo1

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
