apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
spec:
  clusterIP: None # This makes it a headless service
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password123"
          volumeMounts:
            - name: mongo-hostpath-storage
              mountPath: /data/db
      volumes:
        - name: mongo-hostpath-storage
          hostPath:
            # This path is inside the Minikube VM, where we mounted our local folder
            path: /data/mongo-storage
            type: DirectoryOrCreate 